export const HTTP_STEP_EMPTY = -1;
export const HTTP_STEP_REQUEST_START = 0;
export const HTTP_STEP_REQUEST_START_LINE = 1;
export const HTTP_STEP_REQUEST_HEADER = 2;
export const HTTP_STEP_REQUEST_WEBSOCKET_CONNECTION = 5;

export const HTTP_STEP_REQUEST_BODY = 8;
export const HTTP_STEP_REQUEST_END = 9;
export const HTTP_STEP_REQUEST_CONTENT_WAIT_CONSUME = 10;
export const HTTP_STEP_REQUEST_COMPLETE = 11;

export const HTTP_STEP_RESPONSE_WAIT = 20;
export const HTTP_STEP_RESPONSE_START = 21;
export const HTTP_STEP_RESPONSE_HEADER_SPEND = 22;
export const HTTP_STEP_RESPONSE_READ_CONTENT_CHUNK = 23;
export const HTTP_STEP_RESPONSE_READ_CONTENT_END = 24;
export const HTTP_STEP_RESPONSE_END = 30;
export const HTTP_STEP_RESPONSE_ERROR = 91;
