export default () => ({
  request: {
    dateTimeCreate: Date.now(),
    timeOnStart: performance.now(),
    timeOnStartLine: null,
    timeOnHeader: null,
    timeOnBody: null,
    timeOnEnd: null,
    connection: false,
    method: null,
    path: null,
    httpVersion: null,
    headersRaw: [],
    headers: {},
    body: null,
    pathname: null,
    querystring: '',
    query: {},
  },
  response: null,
  error: null,
});
